name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testOnPR:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy test environment variables
        run: cp example.env .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: disable and stop mono-xsp4.service
        run: |
          sudo systemctl stop mono-xsp4.service || true
          sudo systemctl disable mono-xsp4.service || true
       
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run dev server
        run: yarn start --sources 'packages/esm-*-app'
      
      - name: Run E2E tests
        run: yarn playwright test

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  testOnPush:
    if: ${{ github.event_name == 'push' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy test environment variables
        run: cp example.env .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run db and web containers
        run: |
          cd e2e/support
          docker-compose up -d

      - name: Run dev server
        run: yarn start --sources 'packages/esm-*-app/' --backend "http://localhost:9000" &

      - name: Run E2E tests
        run: yarn playwright test

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
